### ISSUE TITLE
Cannot read property 'pipesCount' of undefined

### ISSUE THREAD

**Issue by Thomptronics** [cplee/lambda-express#6]
As per a previously reported issue (https://github.com/cplee/lambda-express/issues/1), I am getting the following error when the express app is called by your appHandler:

TypeError: Cannot read property 'pipesCount' of undefined
at IncomingMessage.Readable.unpipe (_stream_readable.js:611:12)
at unpipe (/var/task/node_modules/express/node_modules/finalhandler/node_modules/unpipe/index.js:47:12)
at send (/var/task/node_modules/express/node_modules/finalhandler/index.js:184:3)
at Immediate.<anonymous> (/var/task/node_modules/express/node_modules/finalhandler/index.js:113:5)
at Immediate.<anonymous> (/var/task/node_modules/express/lib/router/index.js:618:15)
at Immediate.immediate._onImmediate (timers.js:435:18)
at processImmediate [as _immediateCallback] (timers.js:383:17)

I am using version 4.14.0 of express.

Any help would be greatly appreciated.

Thanks,
-Randy

**Comment by rahulkalidindi** [comment]
Facing similar issue when tried to integrate Express to Lambda

TypeError: Cannot read property 'indexOf' of undefined
    at Function.handle (/var/task/node_modules/express/lib/router/index.js:140:27)
    at EventEmitter.handle (/var/task/node_modules/express/lib/application.js:173:10)
    at /var/task/node_modules/lambda-express/index.js:133:13
